# building docker images
- docker build -t udagram-api-feed ./udagram-api-feed
- docker build -t udagram-api-user ./udagram-api-user
- docker build -t udagram-frontend ./udagram-frontend
- docker build -t reverseproxy ./reverseproxy
  
  # Tagging docker images with their respective repositories tag
- docker tag udagram-api-feed idris21/udagram-api-feed:v1
- docker tag udagram-api-user idris21/udagram-api-user:v1
- docker tag udagram-frontend idris21/udagram-frontend:v1
- docker tag reverseproxy idris21/reverseproxy:v1
  
  # pushing docker images to dockerhub repositories
- echo "$DOCKER_PASSWORD". | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push idris21/udagram-api-feed:v1
- docker push idris21/udagram-api-user:v1
- docker push idris21/udagram-frontend:v1
- docker push idris21/reverseproxy:v1
  
