language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests" 

script:
  # building docker images
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy

    # Tagging docker images with their respective repositories tag
  - docker tag udagram-api-feed idris21/udagram-api-feed:v2
  - docker tag udagram-api-user idris21/udagram-api-user:v2
  - docker tag udagram-frontend idris21/udagram-frontend:v2
  - docker tag reverseproxy idris21/reverseproxy:v2

after_success:
    # pushing docker images to dockerhub repositories
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push idris21/udagram-api-feed:v2
  - docker push idris21/udagram-api-user:v2
  - docker push idris21/udagram-frontend:v2
  - docker push idris21/reverseproxy:v2


  
