apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed-deployment
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: idris21/udagram-api-feed:v1
        envFrom:
        - configMapRef:
            name: env-configmap
        - secretRef:
            name: env-secret
        ports:
        - containerPort: 8080

